server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php;

    add_header X-Frame-Options "SAMEORIGIN"           always;
    add_header X-Content-Type-Options "nosniff"       always;
    add_header X-XSS-Protection "1; mode=block"       always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location / {
        limit_req zone=geral burst=20 nodelay;
        proxy_pass http://php:80;
        include /etc/nginx/proxy_params;
    }

    location /login {
        limit_req zone=sensivel burst=5 nodelay;
        proxy_pass http://php:80;
        include /etc/nginx/proxy_params;
    }

    location /signup {
        limit_req zone=sensivel burst=5 nodelay;
        proxy_pass http://php:80;
        include /etc/nginx/proxy_params;
    }

    location ~* \.(env|git|htpasswd|log|sql|bak)$ {
        deny all;
        return 404;
    }
}

server {
    listen 81;
    server_name _;

    auth_basic "Admin Area";
    auth_basic_user_file /etc/nginx/.htpasswd;

    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
        proxy_pass http://phpmyadmin:80;
        include /etc/nginx/proxy_params;
    }
}