worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server_tokens off;

    limit_req_zone $binary_remote_addr zone=geral:10m rate=50r/m;
    limit_req_zone $binary_remote_addr zone=sensivel:10m rate=10r/m;

    limit_req_status 429;

    log_format json escape=json '{"ip":"$remote_addr","time":"$time_iso8601","method":"$request_method","uri":"$request_uri","status":$status,"ua":"$http_user_agent"}';

    access_log /var/log/nginx/access.log json;
    error_log  /var/log/nginx/error.log warn;

    include /etc/nginx/conf.d/*.conf;
}